[build]
  command = "npm run build"
  publish = "./dist/"
[dev]
  command = "npm run dev"
  targetPort = 5173
[functions."api"]
  included_files = ["./netlify/functions/data/bin/**"]
#[functions."scheduled-update-db"]
  #schedule = "@daily"
[[plugins]]
  package = "netlify-plugin-svg-sprite"
  [plugins.inputs]
    dist = "./src/assets/"
[[plugins]]
  package = "./netlify/plugins/netlify-plugin-update-db"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"